class Config:
    # dataset folders
    FRONT_PATH = r'F:\Dataset_3D-FRONT\3D-FRONT'
    FUTURE_PATH = r'F:\Dataset_3D-FRONT\3D-FUTURE-model'
    TEXTURE_PATH = r'F:\Dataset_3D-FRONT\3D-FRONT-texture'

    # output folders
    OUTPUT_JSON = r'F:\Dataset_3D-FRONT\Unity-json'
    OUTPUT_FLOOR = r'F:\Dataset_3D-FRONT\Unity-floor'

    # invalid house
    INVALID_HOUSE = [
        'cd15742e-678b-45ab-af31-050d5c6c97a4',
    ]

    ROOM_TYPE = [
        'Library',
        'MasterBedroom',
        'SecondBedroom',
        'LivingDiningRoom',
        'LivingRoom',
        'Bedroom',
        'DiningRoom',
        'Hallway',
        'Corridor',
        'OtherRoom',
        'KidsRoom',
        'Aisle',
        'CloakRoom',
        'ElderlyRoom',
        'StorageRoom',
        'Terrace',
        'Lounge',
        'BedRoom',
        'EquipmentRoom',
        'LaundryRoom',
        'Stairwell',
        'NannyRoom',
        'Kitchen',
        'Auditorium',
        'Courtyard',
        'Garage',
        'Balcony'
    ]

    OBJ_CATEGORY = [
        'Dressing Table',
        'Lounge Chair / Cafe Chair / Office Chair',
        'Bookcase / jewelry Armoire',
        'Pendant Lamp',
        'King-size Bed',
        'Wardrobe',
        'Drawer Chest / Corner cabinet',
        'Desk',
        'Sideboard / Side Cabinet / Console Table',
        'Sideboard / Side Cabinet / Console',
        'Tea Table',
        'TV Stand',
        'Three-Seat / Multi-seat Sofa',
        'Shoe Cabinet',
        'armchair',
        'Coffee Table',
        'Corner/Side Table',
        'Nightstand',
        'Dining Table',
        'Dining Chair',
        'Lounge Chair / Book-chair / Computer Chair',
        'Ceiling Lamp',
        'Loveseat Sofa',
        'Lazy Sofa',
        'Kids Bed',
        'Children Cabinet',
        'Single bed',
        'Shelf',
        'Dressing Chair',
        'Wine Cooler',
        'Footstool / Sofastool / Bed End Stool / Stool',
        'Round End Table',
        'Barstool',
        'L-shaped Sofa',
        'Three-Seat / Multi-person sofa',
        'Bar',
        'Wine Cabinet',
        'Floor Lamp',
        'Bunk Bed',
        'Double Bed',
        'Folding chair',
        'Classic Chinese Chair',
        'Chaise Longue Sofa',
        'Hanging Chair',
        'U-shaped Sofa',
        'Couch Bed',
        'Bed Frame',
        'Two-seat Sofa',
        'Wall Lamp'
    ]

    SUPP_ROOM_TYPE = [
        'Library',
        'MasterBedroom',
        'SecondBedroom',
        'LivingDiningRoom',
        'LivingRoom',
        'Bedroom',
        'DiningRoom',
        'BedRoom',
    ]

    SUPP_OBJ_CATEGORY = [
        'Dressing Table',
        'Lounge Chair / Cafe Chair / Office Chair',
        'Bookcase / jewelry Armoire',
        'Pendant Lamp',
        'King-size Bed',
        'Wardrobe',
        'Drawer Chest / Corner cabinet',
        'Desk',
        'Sideboard / Side Cabinet / Console Table',
        'Sideboard / Side Cabinet / Console',
        'Tea Table',
        'TV Stand',
        'Three-Seat / Multi-seat Sofa',
        'Shoe Cabinet',
        'armchair',
        'Coffee Table',
        'Corner/Side Table',
        'Nightstand',
        'Dining Table',
        'Dining Chair',
        'Lounge Chair / Book-chair / Computer Chair',
        'Ceiling Lamp',
        'Loveseat Sofa',
        'Lazy Sofa',
        'Kids Bed',
        'Children Cabinet',
        'Single bed',
        'Shelf',
        'Dressing Chair',
        'Wine Cooler',
        'Footstool / Sofastool / Bed End Stool / Stool',
        'Round End Table',
        'Barstool',
        'L-shaped Sofa',
        'Three-Seat / Multi-person sofa',
        'Bar',
        'Wine Cabinet',
        'Floor Lamp',
        'Bunk Bed',
        'Double Bed',
        'Folding chair',
        'Classic Chinese Chair',
        'Chaise Longue Sofa',
        'Hanging Chair',
        'U-shaped Sofa',
        'Couch Bed',
        'Bed Frame',
        'Two-seat Sofa',
        'Wall Lamp'
    ]
